const USERS = [
  {
    username: "patrickstar", 
    email: 'patrickstar@bikinibottom.com',
    mangoCount: 234,
    totalMangosEarned: 500,
    totalClapsEarned: 56,
    tasksCompleted: 0,
    dateJoined: new Date(),
  },
  { username: "SpongeBob", 
    email: 'spongebobhaspants@pineapple.com',
    mangoCount: 100,
    totalMangosEarned: 10003034,
    totalClapsEarned: 1002,
    tasksCompleted: 3,
    dateJoined: new Date(),
  },
  {
    username: "SandyCheeks", 
    email: 'sandycheeks@bikinibottom.com',
    mangoCount: 50034343,
    totalMangosEarned: 2340003400,
    totalClapsEarned: 63,
    tasksCompleted: 100,
    dateJoined: new Date(),
  },
  { username: "Squidward", 
    email: 'squidward@bikinibottom.com',
    mangoCount: 16000,
    totalMangosEarned: 15999,
    totalClapsEarned: 1248,
    tasksCompleted: 54,
    dateJoined: new Date(),
  },
  { username: "MrKrabs", 
    email: 'moneymoneymoney@bikinibottom.com',
    mangoCount: 304304030430,
    totalMangosEarned: 304304030430,
    totalClapsEarned: 9877,
    tasksCompleted: 1,
    dateJoined: new Date(),
  }
];

exports.USERS = USERS;