export const USERS = [
  {
    username: "patrickstar", 
    email: 'patrickstar@bikinibottom.com',
    mangoCount: 234,
    totalMangosEarned: 500,
    dateJoined: new Date(),
  },
  { username: "SpongeBob", 
    email: 'spongebobhaspants@pineapple.com',
    mangoCount: 100,
    totalMangosEarned: 10003034,
    dateJoined: new Date(),
  },
  {
    username: "SandyCheeks", 
    email: 'sandycheeks@bikinibottom.com',
    mangoCount: 50034343,
    totalMangosEarned: 2340003400,
    dateJoined: new Date(),
  },
  { username: "Squidward", 
    email: 'squidward@bikinibottom.com',
    mangoCount: 16000,
    totalMangosEarned: 15999,
    dateJoined: new Date(),
  },
  { username: "MrKrabs", 
    email: 'moneymoneymoney@bikinibottom.com',
    mangoCount: 304304030430,
    totalMangosEarned: 304304030430,
    dateJoined: new Date(),
  }
];
